### ISSUE TITLE
Python workbench: don't compile python on first login

### ISSUE THREAD

**Issue by dometto** [UtrechtUniversity/researchcloud-items#117]
The `pyenv` role currently installs a specific python version for each user when they first login. This is much too slow, because python needs to be compiled from the ground up.

**Comment by dometto** [comment]
We can install pyenv but let it use the default system python by default. The user can install their own desired python versions via pyenv in that case.

However, on Ubuntu the default python version is a bit old:

* 3.8.10 on Ubuntu 20
* 3.10.12 on Ubuntu 22

Now Ubuntu lets us `apt install` extra python versions: 3.9.5 on Ubuntu 20, 3.11 on Ubuntu 22. That's a bit better. :) However, these versions will not be used by default: the user has to explicitly call for example `/usr/bin/python3.11`.

One idea is to use [this simple pyenv plugin](https://github.com/garyp/pyenv-register) to make `pyenv` recognise the extra python versions installed with `apt`. In that case, we could set things up so that users of the Python Workbench workspaces get the newest possible python installed via `apt` when they simply type `python`.

Downsides: the plugin does not look super well maintained. It's simple so it may just work, and we can fork it ourselves for security purposes.

The only alternative I see is to simply document that `/usr/bin/python3.9` (Focal) and `/usr/bin/python3.11` are also available, and instruct the user to install their own python versions.

**Comment by dometto** [comment]
@chStaiger @jelletreep would appreciate a second opinion on this -- what do you think is the most friendly to our users?

**Comment by jelletreep** [comment]
I would say 3.8 and 3.10 are ok in many cases, and we could add a paragraph in the documentation about installing different python versions and linking to the pyenv documentation. The cases where 3.8 is not ok, I would expect often the user might need a specific version other than 3.9.5

**Comment by jelletreep** [comment]
BTW great that you are removing the per user installation of python and reducing the creation time!
