### ISSUE TITLE
Add iBridges component to our catalog items

### ISSUE THREAD

**Issue by dometto** [UtrechtUniversity/researchcloud-items#121]
Add the `iRODS Tools` (installs icommands + ibridges) or `iBridges` (just installs ibridges) component to our catalog items that need it:

- [x] Python Workbench
- [x] Matlab
- [x] Stata
- [x] Miniconda
- [x] ? Whisper

Remove `irods-desktop` from:

- [x] Stata
- [x] Matlab

(Should update users first that they can use iBridges instead)

After that:

- [ ] Remove irods-desktop role and playbook

**Comment by jelletreep** [comment]
Seems useful for Jupyter and Rstudio as well, but they are managed by SURF.
For Jupyter this could be achieved with custom packages as well, not sure if that is the best option though
For Rstudio I think there is still not a good way to manage package preinstallations

**Comment by dometto** [comment]
We're in touch with SURF to eventually hopefully make iBridges available on their Catalog Items as well! If that doesn't work out, it may also be an option to create our own catalog items (but use the SURF components).
