### ISSUE TITLE
remove miniconda-base

### ISSUE THREAD

**Issue by jelletreep** [UtrechtUniversity/researchcloud-items#32]
miniconda-base is outdated and probably not used in any plugins (this need to be checked). Remove when confirmed.

- [ ] Check if miniconda-base is used in any plug ins
- [ ] remove playbook and other relevant files

**Comment by geekedpriest** [comment]
I need some help I just got the Omen 15 Gaming, 10th Gen Intel Core 17,16GB
RAM,1TB SSD, 6GB RTX Graphics, 15.6" Win 10 with Nividia graphics, I'm trying to install the Avartarify through miniconda I have followed all the instructions been on it for 5hrs now still not working. I get to a point where I don't understand and it isn't part of the explanation... I need help pls ![image](https://user-images.githubusercontent.com/120290986/206884845-a440773c-df9f-4234-8037-bcdb8cb151ea.png)


![Uploading 206884857...]


![image](https://user-images.githubusercontent.com/120290986/206884864-563696cb-6f1c-4f2b-a131-e81e9bfe42b2.jpeg)


I need help getting past that point I don't know what to do.

**Comment by dometto** [comment]
@jelletreep should we still do this? I think we could also leave miniconda-base in the repository, in case we ever want to use it -- unless miniconda itself is outdated/deprecated?

**Comment by jelletreep** [comment]
@dometto, There are 2 miniconda playbooks, miniconda-base and miniconda. Miniconda-base is something I created and it is just a plain install script, while the other one was created by someone else and includes options to install system wide or per user. Whenever there is time for it we can maybe discuss what would be a good solution and then remove what we don't use anymore

**Comment by dometto** [comment]
CLosed by #131
