### ISSUE TITLE
plugins 

### ISSUE THREAD

**Issue by jelletreep** [UtrechtUniversity/researchcloud-items#36]
Jelle:
- [ ] agisoft metashape
- [x] anaconda navigator
- [x] miniconda
- [ ] owncloud
- [ ] pip
- [x] poetry
- [ ] pyenv
- [x] TORS plugins (not in this repo, but should be kept a little longer. These are developed for TORS project which is still running)

Ton:
- [x] asreview
- [ ] Camunda server
- [x] Docker tools
- [ ] Ephor
- [x] irods-desktop
- [x] irods-icommands
- [x] Keycloak
- [x] Matlab
- [x] python workbench
- [x] robot client
- [x] robot server
- [ ] ton plugin test
- [ ] ton private plugin test
- [x] tweet collector

**Comment by chStaiger** [comment]
I am not allowed to edit the text above. So here my status.
- Waiting for key cloak
- Waiting for Miniconda

to roll out.

**Comment by tsmeele** [comment]
finding: poetry failed to install in a matlab workbench (error log in user home dir), due to incompatibilities with dependencies.
