### ISSUE TITLE
A more permissive license

### ISSUE THREAD

**Issue by J535D165** [UtrechtUniversity/researchcloud-items#8]
Thanks for the work on this repo. Very useful. 

The strong copyleft license of this repo limits us to reuse of scripts in this repo (especially ASReview). What do you think about a more permissive license like MIT?

**Comment by tsmeele** [comment]
Our repo configuration allows for the use of alternative licenses on a per-role basis, please see README for procedure.
Would an MIT on role ASReview be sufficient for your use case?

**Comment by dometto** [comment]
@J535D165 was this ever resolved?

**Comment by J535D165** [comment]
As far as I know not :)

**Comment by dometto** [comment]
@J535D165 if you still need any of these scripts under a different license!
