### ISSUE TITLE
Remove hardcoded occurrences of volume names

### ISSUE THREAD

**Issue by dometto** [UtrechtUniversity/researchcloud-items#88]
SURF is making the names of network volume drives dynamic and configurable, instead of the current situation in which volumes are always mounted under `/data/volume_1` etc. Some of our components reference these hardcoded paths. This should be remedied. See [here](https://servicedesk.surf.nl/wiki/pages/viewpage.action?pageId=96207403) for an explanation of the new situation.

**Comment by dometto** [comment]
@jelletreep the Whisper role refers to `/data/volume_2`, but it appears to be just an example: https://github.com/UtrechtUniversity/researchcloud-items/blob/main/playbooks/roles/whisper/files/whisper_template.ipynb

Can we just change the wording of the example in the template, or are there any implicit dependencies on that path in the code?

**Comment by jelletreep** [comment]
Yes in the whisper notebook it is just instruction, I will revise it!
